/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsYatraNotesRouteImport } from './routes/projects.yatra-notes'
import { Route as ProjectsProductEvaluationHarnessRouteImport } from './routes/projects.product-evaluation-harness'
import { Route as ProjectsAxionAiRouteImport } from './routes/projects.axion-ai'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsYatraNotesRoute = ProjectsYatraNotesRouteImport.update({
  id: '/projects/yatra-notes',
  path: '/projects/yatra-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProductEvaluationHarnessRoute =
  ProjectsProductEvaluationHarnessRouteImport.update({
    id: '/projects/product-evaluation-harness',
    path: '/projects/product-evaluation-harness',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsAxionAiRoute = ProjectsAxionAiRouteImport.update({
  id: '/projects/axion-ai',
  path: '/projects/axion-ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRoute
  '/projects/axion-ai': typeof ProjectsAxionAiRoute
  '/projects/product-evaluation-harness': typeof ProjectsProductEvaluationHarnessRoute
  '/projects/yatra-notes': typeof ProjectsYatraNotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRoute
  '/projects/axion-ai': typeof ProjectsAxionAiRoute
  '/projects/product-evaluation-harness': typeof ProjectsProductEvaluationHarnessRoute
  '/projects/yatra-notes': typeof ProjectsYatraNotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRoute
  '/projects/axion-ai': typeof ProjectsAxionAiRoute
  '/projects/product-evaluation-harness': typeof ProjectsProductEvaluationHarnessRoute
  '/projects/yatra-notes': typeof ProjectsYatraNotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/work'
    | '/projects/axion-ai'
    | '/projects/product-evaluation-harness'
    | '/projects/yatra-notes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/work'
    | '/projects/axion-ai'
    | '/projects/product-evaluation-harness'
    | '/projects/yatra-notes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/work'
    | '/projects/axion-ai'
    | '/projects/product-evaluation-harness'
    | '/projects/yatra-notes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  WorkRoute: typeof WorkRoute
  ProjectsAxionAiRoute: typeof ProjectsAxionAiRoute
  ProjectsProductEvaluationHarnessRoute: typeof ProjectsProductEvaluationHarnessRoute
  ProjectsYatraNotesRoute: typeof ProjectsYatraNotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/yatra-notes': {
      id: '/projects/yatra-notes'
      path: '/projects/yatra-notes'
      fullPath: '/projects/yatra-notes'
      preLoaderRoute: typeof ProjectsYatraNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/product-evaluation-harness': {
      id: '/projects/product-evaluation-harness'
      path: '/projects/product-evaluation-harness'
      fullPath: '/projects/product-evaluation-harness'
      preLoaderRoute: typeof ProjectsProductEvaluationHarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/axion-ai': {
      id: '/projects/axion-ai'
      path: '/projects/axion-ai'
      fullPath: '/projects/axion-ai'
      preLoaderRoute: typeof ProjectsAxionAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  WorkRoute: WorkRoute,
  ProjectsAxionAiRoute: ProjectsAxionAiRoute,
  ProjectsProductEvaluationHarnessRoute: ProjectsProductEvaluationHarnessRoute,
  ProjectsYatraNotesRoute: ProjectsYatraNotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
